mentorList = [{
			"password": "password",
			"firstname": "Jack",
			"lastname": "Daniels",
			"email": "jdaniels@gmail.com",
			"bio": "I love mentoring!!!",
			"school": "Rutgers University",
			"birthdate": "08/08/1995",
			"hobbies": "volleyball, tennis",
			"company": "Facebook",
			"ethnicity": "African American",
			"gender": "Male",
			"position": "Data Scientist",
			"degree": "Satistics",
			"city": "Princeton",
			"state": "New Jersey",
			"ismentor": True,
			"ismentee": False,
			"mentoravailability": True,
			"menteeavailability": False,
			"pendingmentors": list(),
			"pendingmentees": list(),
			"mentors": list(),
			"mentees": list(),
			"potentialmentors": list()

		},
		{
			"password": "password",
			"firstname": "Michael",
			"lastname": "Jordan",
			"email": "mj@gmail.com",
			"bio": "I love coding and basketball!",
			"school": "Princeton University",
			"birthdate": "07/07/1994",
			"hobbies": "basketball, golf",
			"company": "Google" ,
			"ethnicity": "African American",
			"gender": "Male",
			"position": "Software Engineer",
			"degree": "Computer Science",
			"city": "Princeton",
			"state": "New Jersey",
			"ismentor": True,
			"ismentee": False,
			"mentoravailability": True,
			"menteeavailability": False,
			"pendingmentors": list(),
			"pendingmentees": list(),
			"mentors": list(),
			"mentees": list(),
			"potentialmentors": list()

		},
		{
			"password": "password",
			"firstname": "Rosa",
			"lastname": "Parks",
			"email": "rp@gmail.com",
			"bio": "I love taking bus rides",
			"school": "Stanford University",
			"birthdate": "06/06/1993",
			"hobbies": "League of Legends",
			"company": "Facebook",
			"ethnicity": "African American",
			"gender": "Female",
			"position": "Software Engineer",
			"degree": "Computer Science",
			"city": "New York City",
			"state": "New York",
			"ismentor": True,
			"ismentee": False,
			"mentoravailability": True,
			"menteeavailability": False,
			"pendingmentors": list(),
			"pendingmentees": list(),
			"mentors": list(),
			"mentees": list(),
			"potentialmentors": list()

		},
		{
			"password": "password",
			"firstname": "Alexis",
			"lastname": "Kennedy",
			"email": "aken@gmail.com",
			"bio": "I love playing soccer",
			"school": "Stanford",
			"birthdate": "O6/06/1993",
			"hobbies": "soccer, yugioh",
			"company": "MongoDB",
			"ethnicity": "African American",
			"gender": "Female",
			"position": "Data Scientist",
			"degree": "Mathematics",
			"city": "San Jose",
			"state": "California",
			"ismentor": True,
			"ismentee": False,
			"mentoravailability": True,
			"menteeavailability": False,
			"pendingmentors": list(),
			"pendingmentees": list(),
			"mentors": list(),
			"mentees": list(),
			"potentialmentors": list()

		}]
		# {
		# 	"password": password,
		# 	"firstname": firstname,
		# 	"lastname": lastname,
		# 	"email": email,
		# 	"bio": bio,
		# 	"school": school,
		# 	"birthdate": birthdate,
		# 	"hobbies": hobbies,
		# 	"company": company,
		# 	"ethnicity": ethnicity,
		# 	"gender": gender,
		# 	"position": position,
		# 	"degree": degree,
		# 	"city": city,
		# 	"state": state,
		# 	"ismentor": ismentor,
		# 	"ismentee": ismentee,
		# 	"mentoravailability": mentoravailability,
		# 	"menteeavailability": menteeavailability,
		# 	"pendingmentors": list(),
		# 	"pendingmentees": list(),
		# 	"mentors": list(),
		# 	"mentees": list(),
		# 	"potentialmentors": list()

		# },
		# {
		# 	"password": password,
		# 	"firstname": firstname,
		# 	"lastname": lastname,
		# 	"email": email,
		# 	"bio": bio,
		# 	"school": school,
		# 	"birthdate": birthdate,
		# 	"hobbies": hobbies,
		# 	"company": company,
		# 	"ethnicity": ethnicity,
		# 	"gender": gender,
		# 	"position": position,
		# 	"degree": degree,
		# 	"city": city,
		# 	"state": state,
		# 	"ismentor": ismentor,
		# 	"ismentee": ismentee,
		# 	"mentoravailability": mentoravailability,
		# 	"menteeavailability": menteeavailability,
		# 	"pendingmentors": list(),
		# 	"pendingmentees": list(),
		# 	"mentors": list(),
		# 	"mentees": list(),
		# 	"potentialmentors": list()

		# },
		# {
		# 	"password": password,
		# 	"firstname": firstname,
		# 	"lastname": lastname,
		# 	"email": email,
		# 	"bio": bio,
		# 	"school": school,
		# 	"birthdate": birthdate,
		# 	"hobbies": hobbies,
		# 	"company": company,
		# 	"ethnicity": ethnicity,
		# 	"gender": gender,
		# 	"position": position,
		# 	"degree": degree,
		# 	"city": city,
		# 	"state": state,
		# 	"ismentor": ismentor,
		# 	"ismentee": ismentee,
		# 	"mentoravailability": mentoravailability,
		# 	"menteeavailability": menteeavailability,
		# 	"pendingmentors": list(),
		# 	"pendingmentees": list(),
		# 	"mentors": list(),
		# 	"mentees": list(),
		# 	"potentialmentors": list()

		# },
		# {
		# 	"password": password,
		# 	"firstname": firstname,
		# 	"lastname": lastname,
		# 	"email": email,
		# 	"bio": bio,
		# 	"school": school,
		# 	"birthdate": birthdate,
		# 	"hobbies": hobbies,
		# 	"company": company,
		# 	"ethnicity": ethnicity,
		# 	"gender": gender,
		# 	"position": position,
		# 	"degree": degree,
		# 	"city": city,
		# 	"state": state,
		# 	"ismentor": ismentor,
		# 	"ismentee": ismentee,
		# 	"mentoravailability": mentoravailability,
		# 	"menteeavailability": menteeavailability,
		# 	"pendingmentors": list(),
		# 	"pendingmentees": list(),
		# 	"mentors": list(),
		# 	"mentees": list(),
		# 	"potentialmentors": list()

		# },
		# {
		# 	"password": password,
		# 	"firstname": firstname,
		# 	"lastname": lastname,
		# 	"email": email,
		# 	"bio": bio,
		# 	"school": school,
		# 	"birthdate": birthdate,
		# 	"hobbies": hobbies,
		# 	"company": company,
		# 	"ethnicity": ethnicity,
		# 	"gender": gender,
		# 	"position": position,
		# 	"degree": degree,
		# 	"city": city,
		# 	"state": state,
		# 	"ismentor": ismentor,
		# 	"ismentee": ismentee,
		# 	"mentoravailability": mentoravailability,
		# 	"menteeavailability": menteeavailability,
		# 	"pendingmentors": list(),
		# 	"pendingmentees": list(),
		# 	"mentors": list(),
		# 	"mentees": list(),
		# 	"potentialmentors": list()

		# },
		# {
		# 	"password": password,
		# 	"firstname": firstname,
		# 	"lastname": lastname,
		# 	"email": email,
		# 	"bio": bio,
		# 	"school": school,
		# 	"birthdate": birthdate,
		# 	"hobbies": hobbies,
		# 	"company": company,
		# 	"ethnicity": ethnicity,
		# 	"gender": gender,
		# 	"position": position,
		# 	"degree": degree,
		# 	"city": city,
		# 	"state": state,
		# 	"ismentor": ismentor,
		# 	"ismentee": ismentee,
		# 	"mentoravailability": mentoravailability,
		# 	"menteeavailability": menteeavailability,
		# 	"pendingmentors": list(),
		# 	"pendingmentees": list(),
		# 	"mentors": list(),
		# 	"mentees": list(),
		# 	"potentialmentors": list()

		# }
		# ]

from ManDB import ManDB
user_db = ManDB()

for i in mentorList:
	user_db.createUser(**i)