mentorList = [{
			"password": "password",
			"firstname": "Jack",
			"lastname": "Daniels",
			"email": "jdaniels@gmail.com",
			"bio": "I love mentoring!!!",
			"school": "Rutgers University",
			"birthdate": "08/08/1995",
			"hobbies": "volleyball, tennis",
			"company": "Facebook",
			"ethnicity": "African American",
			"gender": "Male",
			"position": "Data Scientist",
			"degree": "Satistics",
			"city": "Princeton",
			"state": "New Jersey",
			"ismentor": True,
			"ismentee": False,
			"mentoravailability": True,
			"menteeavailability": False

		},
		{
			"password": "password",
			"firstname": "Michael",
			"lastname": "Jordan",
			"email": "mjordan@gmail.com",
			"bio": "I love coding and basketball!",
			"school": "Princeton University",
			"birthdate": "07/07/1994",
			"hobbies": "basketball, golf",
			"company": "Google" ,
			"ethnicity": "African American",
			"gender": "Male",
			"position": "Software Engineer",
			"degree": "Computer Science",
			"city": "Princeton",
			"state": "New Jersey",
			"ismentor": True,
			"ismentee": False,
			"mentoravailability": True,
			"menteeavailability": False

		},
		{
			"password": "password",
			"firstname": "Rosa",
			"lastname": "Parks",
			"email": "rparks@gmail.com",
			"bio": "I love taking bus rides",
			"school": "Stanford University",
			"birthdate": "06/06/1993",
			"hobbies": "League of Legends",
			"company": "Facebook",
			"ethnicity": "African American",
			"gender": "Female",
			"position": "Software Engineer",
			"degree": "Computer Science",
			"city": "New York City",
			"state": "New York",
			"ismentor": True,
			"ismentee": False,
			"mentoravailability": True,
			"menteeavailability": False

		},
		{
			"password": "password",
			"firstname": "Alexis",
			"lastname": "Kennedy",
			"email": "aken@gmail.com",
			"bio": "I love playing soccer",
			"school": "Rutgers University",
			"birthdate": "O6/06/1993",
			"hobbies": "soccer, yugioh",
			"company": "MongoDB",
			"ethnicity": "African American",
			"gender": "Female",
			"position": "Data Scientist",
			"degree": "Mathematics",
			"city": "San Jose",
			"state": "California",
			"ismentor": True,
			"ismentee": False,
			"mentoravailability": True,
			"menteeavailability": False

		},
		{
			"password": "password",
			"firstname": "Emilia",
			"lastname": "Sanchez",
			"email": "eSanchez@gmail.com",
			"bio": "I love cooking all sorts of cusine",
			"school": "Olin College",
			"birthdate": "08/08/1994",
			"hobbies": "cooking, reading",
			"company": "MongoDB",
			"ethnicity": "Hispanic",
			"gender": "Female",
			"position": "Software Engineer",
			"degree": "Computer Engineering",
			"city": "San Francisco",
			"state": "California",
			"ismentor": True,
			"ismentee": False,
			"mentoravailability": True,
			"menteeavailability": False

		},
		{
			"password": "password",
			"firstname": "Juan",
			"lastname": "Suarez",
			"email": "jsuarez@gmail.com",
			"bio": "I love watching soccer",
			"school": "Olin College",
			"birthdate": "08/08/1995",
			"hobbies": "soccer, anime",
			"company": "Sephora",
			"ethnicity": "Hispanic",
			"gender": "Male",
			"position": "Web Developer",
			"degree":"Mathematics" ,
			"city": "Boston",
			"state": "Massachusetts",
			"ismentor": True,
			"ismentee": False,
			"mentoravailability": True,
			"menteeavailability": False

		},
		{
			"password": "password",
			"firstname": "Camila",
			"lastname": "Martinez",
			"email": "email",
			"bio": "I love going out every weekend",
			"school": "UCLA",
			"birthdate": "08/08/1995",
			"hobbies": "",
			"company": "Two Sigma",
			"ethnicity": "Hispanic",
			"gender": "Female",
			"position": "Quantiative Analyst",
			"degree": "Mathematics",
			"city": "New York City",
			"state": "New York",
			"ismentor": True,
			"ismentee": False,
			"mentoravailability": True,
			"menteeavailability": False

		},
		{
			"password": "password",
			"firstname": "Jessica",
			"lastname": "Yang",
			"email": "jyang@gmail.com",
			"bio": "I like to study mathematics",
			"school": "MIT",
			"birthdate": "08/08/1992",
			"hobbies": "Math, Math, Math",
			"company": "Apple",
			"ethnicity": "Asain" ,
			"gender": "Female",
			"position": "Data Scientist",
			"degree": "Mathematics",
			"city": "San Jose",
			"state": "California",
			"ismentor": True,
			"ismentee": False,
			"mentoravailability": True,
			"menteeavailability": False

		},
		{
			"password": "passoword",
			"firstname": "Kimberly",
			"lastname": "Wong",
			"email": "kWong@gmail.com",
			"bio": "I like to play tennis",
			"school": "Rutgers University",
			"birthdate": "06/06/1994",
			"hobbies": "Tennis, Chess",
			"company": "Jane Street",
			"ethnicity": "Asian",
			"gender": "Female",
			"position": "Quantitative Analyst",
			"degree": "Philosphy",
			"city": "New York City",
			"state": "New York",
			"ismentor": True,
			"ismentee": False,
			"mentoravailability": True,
			"menteeavailability": False

		},
		{
			"password": "password",
			"firstname": "Chandini",
			"lastname": "Patel",
			"email": "cPatel@gmail.com",
			"bio": "I enjoylong walks on the beach",
			"school": "RIT",
			"birthdate": "08/08/1994",
			"hobbies": "Dance, Sketching",
			"company": "Boston Consulting Group",
			"ethnicity": "Asian",
			"gender": "Female",
			"position": "Project Manager",
			"degree": "Finance",
			"city": "Boston",
			"state": "Massachusetts",
			"ismentor": True,
			"ismentee": False,
			"mentoravailability": True,
			"menteeavailability": False

		}
		]

from ManDB import ManDB
user_db = ManDB()

for i in mentorList:
	user_db.createUser(**i)